model:
  n_layer: 1
  n_head: 1
  n_embd: 256
  linear: True

data:
  name: 'add'
  n: 4
  reverse: True
  cot: False
  n_train: 256
  n_test: 64
  fixed_len: True

train:
  lr: 0.0001 
  grad_clip: -1
  num_steps: 10000
  norm_type: "none_rank"
  wandb: True
  save_ckpt: False
  ckpt_freq: 20
