model:
  n_layer: 1
  n_head: 2
  n_embd: 256
  linear: True
  vocab_size: 20

data:
  tasks:
    - name: MovingWindowSum
      task: MovingWindowSum
      k: 3
      max_num: 16
      min_num: 1
      n_test: 32
      n_train: 128
      p: 17
      sep: 17
  num_tokens: 16
  mix: random

train:
  lr: 0.0001
  grad_clip: -1
  num_steps: 5000
  mask_input: true
  freeze_embedding: false
  save_ckpt: true
  ckpt_freq: 20
  ckpt_path: './ckpts/mws_linear_k3_2heads.tar'
  seed: 67
  stop_on_perfect_acc: true
  perfect_acc_patience: 50
  wandb: true
  watch_log_freq: 10
  wandb_project: loss_plateau_tf
  wandb_run_name: mix_Sumk3_5kSteps_2heads
